### ISSUE TITLE
Not working. Daemon problem.

### ISSUE THREAD

**Issue by elsedar** [aspenluxxxy/xenon-docs#4] opened 2021-03-02 21:47 UTC
## Setup (please complete the following information):
 - **iOS Version**: 
 - **Jailbreak used**: 
 - **Computer OS**:

**Comment by aspenluxxxy** [comment] 2021-03-02 21:53
Try the fix detailed in the documentation:

> In tweak version 1.0.0, there is a major bug that occurs on new installs, resulting in "Xenon Daemon not running".
> 
> There are two ways to fix this:
> 
> - Create the /var/mobile/Library/me.aspenuwu.xenon folder in Filza
> 
> OR
> 
> - Run the following commands over SSH:
> ```bash
> mkdir /var/mobile/Library/me.aspenuwu.xenon
> chown mobile /var/mobile/Library/me.aspenuwu.xenon
> ```
> The chown is not needed if you are SSH'd in as the `mobile` user, but it IS needed if you are `root`.

This will be fixed as soon as my 1.0.1 build is approved and pushed.

**Comment by aspenluxxxy** [comment] 2021-03-02 23:58
duplicate of https://github.com/aspenluxxxy/xenon-docs/issues/2

**Closed by aspenluxxxy** 2021-03-02 23:58 UTC
Labels: bug, duplicate
